[AutoRun]
enabled=false

[BitTorrent]
Session\GlobalMaxRatio=1
Session\GlobalMaxSeedingMinutes=1440
Session\MaxRatioAction=0
Session\TempPathEnabled=false

[Preferences]
Bittorrent\MaxConnecs=500
Bittorrent\MaxConnecsPerTorrent=100
Bittorrent\MaxUploads=100
Bittorrent\MaxUploadsPerTorrent=5
Connection\PortRangeMin=6881
Connection\UPnP=false
Downloads\PreAllocation=true
Downloads\TempPathEnabled=false
General\Locale=en
Queueing\MaxActiveDownloads=5
Queueing\MaxActiveTorrents=10
Queueing\MaxActiveUploads=5
Queueing\QueueingEnabled=true
WebUI\AuthSubnetWhitelist=172.16.0.0/12
WebUI\AuthSubnetWhitelistEnabled=true
WebUI\CSRFProtection=true
WebUI\ClickjackingProtection=true
WebUI\LocalHostAuth=false
WebUI\Port=8080
WebUI\SecureCookie=true
WebUI\ServerDomains=*
WebUI\SessionTimeout=3600
